def lint_paths_json(paths: list[str], config_path: str | None) -> str: ...
def render_lint(
    paths: list[str], config_path: str | None, output_format: str
) -> str: ...
def rules_json() -> str: ...
def formats_json() -> str: ...
