---
# used for publishing documentation on push to main or published release
name: publish docs

on:
  push:
    branches:
      - main
  release:
    types:
      - published

permissions:
  contents: read

jobs:
  build:
    # only build and deploy docs if the actor is not dependabot
    if: ${{ github.actor != 'dependabot[bot]' }}
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-python@v6.3.0
        with:
          python-version: "3.11"
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v8.2.0
        with:
          enable-cache: false
      - name: Build documentation
        run: |
          mkdir -p pages
          touch pages/.nojekyll
          cd docs
          uv run --frozen --group docs sphinx-build -W -b html src build
          # remove any doctrees dirs which aren't needed for publishing
          find ./build -type d -name '.doctrees' -exec rm -rf {} +
          cp -r build/* ../pages/
      - name: Deploy documentation
        uses: JamesIves/github-pages-deploy-action@v4.8.0
        with:
          branch: pages
          folder: pages
